//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCheckinDetail
    {
        [Display(Name = "Mã chi tiết hóa đơn nhập")]
        public int PK_iCheckinDetailID { get; set; }
        [Display(Name = "Mã phiếu nhập")]
        public int FK_iImportOrderID { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public int FK_iProductID { get; set; }
        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        public int iQuatity { get; set; }
        [Display(Name = "Giá nhập")]
        [Required(ErrorMessage = "Vui lòng nhập giá nhập")]
        public double fPrice { get; set; }
    
        public virtual tblImportOrder tblImportOrder { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
