//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMaterSize
    {
        [Display(Name = "Mã danh mục")]
        public int PK_iMaterSizeID { get; set; }
        [Display(Name = "Mã nguyên liệu")]
        public int FK_iMaterialID { get; set; }
        [Display(Name = "Kích thước")]
        [Required(ErrorMessage = "Vui lòng nhập kích thước nguyên liệu")]
        public string sMaterSize { get; set; }

        public virtual tblMaterial tblMaterial { get; set; }
    }
}
