//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMaterPriceImport
    {
        [Display(Name = "Mã chi tiết nguyên liệu nhập")]
        public int PK_iMaterPriceImportID { get; set; }
        [Display(Name = "Mã nguyên liệu")]
        public int FK_iMaterialID { get; set; }
        [Display(Name = "Giá nguyên liệu nhập")]
        [Required(ErrorMessage = "Vui lòng nhập giá nhập")]
        public double fMaterPriceImport { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        public Nullable<System.DateTime> dtStartDay { get; set; }
        [Display(Name = "Ngày kết thúc")]
        public Nullable<System.DateTime> dtEndDay { get; set; }

        public virtual tblMaterial tblMaterial { get; set; }
    }
}
