//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblCheckoutDetails = new HashSet<tblCheckoutDetail>();
        }
        [Display(Name = "Mã hóa đơn bán")]
        public int PK_iOrderID { get; set; }
        [Display(Name = "Mã tài khoản")]
        public int FK_iAccountID { get; set; }
        [Display(Name = "Tên khách hàng")]
        public string sCustomerName { get; set; }
        [Display(Name = "SĐT khách hàng")]
        public string sCustomerPhone { get; set; }
        [Display(Name = "Địa chỉ giao hàng")]
        public string sDeliveryAddress { get; set; }
        [Display(Name = "Ngày lập")]
        public Nullable<System.DateTime> dInvoidDate { get; set; }
        [Display(Name = "Người lập")]
        public string sBiller { get; set; }
        [Display(Name = "Hình thức thanh toán")]
        public Nullable<int> iDeliveryMethod { get; set; }
        [Display(Name = "Phụ phí")]
        public Nullable<double> fSurcharge { get; set; }
        [Display(Name = "Đã thanh toán")]
        public Nullable<int> iPaid { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<int> iState { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCheckoutDetail> tblCheckoutDetails { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
