//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblCheckinDetails = new HashSet<tblCheckinDetail>();
            this.tblCheckoutDetails = new HashSet<tblCheckoutDetail>();
            this.tblImages = new HashSet<tblImage>();
            this.tblReviews = new HashSet<tblReview>();
            this.tblProductColors = new HashSet<tblProductColor>();
            this.tblProductPrices = new HashSet<tblProductPrice>();
            this.tblProductSizes = new HashSet<tblProductSize>();
        }

        [Display(Name = "Mã sản phẩm")]
        public int PK_iProductID { get; set; }
        [Display(Name = "Mã danh mục")]
        public int FK_iCategoryID { get; set; }
        [Display(Name = "Mã khuyến mãi")]
        public int FK_iPromoteID { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public string sProductName { get; set; }
        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả")]
        public string sDescribe { get; set; }
        [Display(Name = "Giá bán")]
        [Required(ErrorMessage = "Vui lòng nhập giá bán")]
        public Nullable<double> fPrice { get; set; }
        [Display(Name = "Màu sắc")]
        public string sColor { get; set; }
        [Display(Name = "Kích thước")]
        public string sSize { get; set; }
        [Display(Name = "Hình ảnh")]
        public string sImage { get; set; }
        [Display(Name = "Đơn vị")]
        [Required(ErrorMessage = "Vui lòng nhập ")]
        public string sUnit { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCheckinDetail> tblCheckinDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCheckoutDetail> tblCheckoutDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImage> tblImages { get; set; }
        public virtual tblPromote tblPromote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReview> tblReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductColor> tblProductColors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductPrice> tblProductPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductSize> tblProductSizes { get; set; }
    }
}
