//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace giadinhthoxinh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblReview
    {
        [Display(Name = "Mã đánh giá")]
        public int PK_iReviewID { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public int FK_iProductID { get; set; }
        [Display(Name = "Mã tài khoản")]
        public int FK_iAccountID { get; set; }
        [Display(Name = "Số sao")]
        public Nullable<int> iStarRating { get; set; }
        [Display(Name = "Thời gian đánh giá")]
        public Nullable<System.DateTime> dtReviewTime { get; set; }

        public virtual tblProduct tblProduct { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
